title: Entrega Visualizacion de Datos PEC2
description: Este es mi repositiorio para la entrega de la PEC 2 de visualizacion de datos
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
